# Generated by Django 5.1.2 on 2024-10-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_rename_gamename_gamecategory_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='title',
            new_name='gamename',
        ),
    ]
