# Generated by Django 5.1.2 on 2024-10-31 14:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_alter_guidedesc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedesc',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.gamecategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='guidedesc',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
